### ISSUE TITLE
Error while building sick_line_guidance package

### ISSUE THREAD

**Issue by pky404** [SICKAG/sick_line_guidance#3]
Unable to build, getting error    
- canopen::ObjectDict::ObjectDictMap’ has not been declared
- ‘object_dictionary_iter’ was not declared in this scope

_`[ 75%] Built target canopen_chain_node
[ 76%] Built target canopen_motor_node
/home/nvidia/test_ws/src/sick_line_guidance/src/sick_line_guidance_eds_util.cpp: In static member function ‘static std::__cxx11::string sick_line_guidance::EdsUtil::readParsePrintEdsfile(const string&)’:
/home/nvidia/test_ws/src/sick_line_guidance/src/sick_line_guidance_eds_util.cpp:97:26: error: **‘canopen::ObjectDict::ObjectDictMap’ has not been declared
     canopen::ObjectDict::ObjectDictMap::const_iterator object_dictionary_iter;**
                          ^
/home/nvidia/test_ws/src/sick_line_guidance/src/sick_line_guidance_eds_util.cpp:98:39: error: ‘object_dictionary_iter’ was not declared in this scope
     while (object_dictionary->iterate(object_dictionary_iter))
                                       ^
sick_line_guidance/CMakeFiles/sick_line_guidance_lib.dir/build.make:230: recipe for target 'sick_line_guidance/CMakeFiles/sick_line_guidance_lib.dir/src/sick_line_guidance_eds_util.cpp.o' failed
make[2]: *** [sick_line_guidance/CMakeFiles/sick_line_guidance_lib.dir/src/sick_line_guidance_eds_util.cpp.o] Error 1
CMakeFiles/Makefile2:5359: recipe for target 'sick_line_guidance/CMakeFiles/sick_line_guidance_lib.dir/all' failed
make[1]: *** [sick_line_guidance/CMakeFiles/sick_line_guidance_lib.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make install -j4 -l4" failed_
`
@rostest @bmerkle

**Comment by michael1309** [comment]
Hi,

can you add information about your operating system, ROS version and PC platform?

**Comment by rostest** [comment]
Hi,

sick_line_guidance has been developed and tested using ROS1 melodic on Ubuntu 18.04. sick_line_guidance uses the canopen drivers provided by https://github.com/ros-industrial/ros_canopen. The ros_canopen repository has different branches for several ros versions. Compile errors might occure if the ros_canopen branch differs from the compiler target. In this case, a specific branch can be checked out by command
```
git clone --branch <branchname> https://github.com/ros-industrial/ros_canopen.git
```
with \<branchname\> melodic-devel, kinetic-devel and so on.

**Comment by pky404** [comment]
Hi,
@michael1309 @rostest 
System information:
Ros Kinetic (1.12.17)
Ubuntu 16.04 LTS
Nvidia jetson Tx2

I am getting this error after adding _sick_line_guidance_ package, (ros_canopen and rest of packages are getting build successfully).

**Comment by pky404** [comment]
Hi @rostest @michael1309 @heizmreSICKAG 

Can anyone please help me with this.

**Comment by rostest** [comment]
Hi @pankaj404,

sorry for a late response. We recommend upgrading to ROS melodic to use sick_line_guidance. 

Background of the build errors are major changes in package ros_canopen for melodic, incl. datatypes like `canopen::ObjectDict::ObjectDictMap`, which are not available in kinetic. An upgrade to melodic is therefore recommanded.
Please let us know, if this option is not viable.

**Comment by pky404** [comment]
Hi @rostest 
Thanks for your reply.
Will be upgrading to melodic.

**Comment by rostest** [comment]
Hi @pankaj404
thanks for your message. I'm closing the ticket, but please feel free to reopen it in case of any other issues or questions.
