### ISSUE TITLE
the ROS node for OLS dies unexpectedly

### ISSUE THREAD

**Issue by ghost** [SICKAG/sick_line_guidance#6]
Hi
I am using the OLS node with bitrate 1.000.000b/s, and it works like a charm. But sometimes the node dies without any particular reason, at least from mu point of view. 
It's a serious problem as we want to have this sick sensor on AGV for assembly process

I put some pictures below. What can be the problem ? thank you

![image](https://user-images.githubusercontent.com/112632382/205335724-80648f41-b6e4-4978-8ed1-2f58ebd5baa2.png)
![image](https://user-images.githubusercontent.com/112632382/205335805-f0862a0c-e268-4251-8535-8ea5e0843fea.png)

**Comment by michael1309** [comment]
After analyzing the report, we have determined that it is a CAN communication issue and thus not a SICK driver issue. We therefore recommend reporting this problem to https://github.com/ros-industrial/ros_canopen.git.

Furthermore you could monitor your application in case of a CAN communication crash, e.g. by monitoring the process directly and additionally adding a "respawn" command when launching the node by the launch file. See the following line as an example of adding the respawn flag.
```
<node name="sick_line_guidance_node" pkg="sick_line_guidance" type="sick_line_guidance_node"  respawn="true">
```
