### ISSUE TITLE
Topic frequency for /ols

### ISSUE THREAD

**Issue by ghost** [SICKAG/sick_line_guidance#7]
Hi
the OLS Sensor works at 200Hz, but the frequency of the /ols topic on my Linux machine is 20-24Hz. I would have expected much higher frequency

Any idea about the reason and about how to increase the frequency ? 

thank you

**Comment by michael1309** [comment]
The transmission speed depends on the process chain set up. Since several sensors may share the CAN bus, it is possible that messages may be lost due to the CAN bus arbitration logic.
