### ISSUE TITLE
Communication errors using two OLS20

### ISSUE THREAD

**Issue by rostest** [SICKAG/sick_line_guidance#8]
sick_line_guidance runs stable with one OLS20, but has communication errors when running with two OLS20. Configuration and logfiles attached: [Test_2xOLS20_125kbps_error.zip](https://github.com/SICKAG/sick_line_guidance/files/14096784/Test_2xOLS20_125kbps_error.zip)

**Comment by ghost** [comment]
Hello,
I've attached two log files. One including the log of the `roslaunch...` command and one of the raw bus data using `candump -ta can0`.

- Init works fine
- First Error in line 2704 at timestamp 1706553192.269867038 in the _roslaunch_log_ file 
- Time can also be found in the raw data log _candump_log_ file

Regarding the _candump_log_ file:
- According to the operating instruction the COBID 0x0180+NodeID (0x0A and 0x0B) is the first TPDO (8 byte) and 0x0280+NodeID the second TPDO (6 byte)
- Default for the CANOpen protocol is that 0x060+NodeID is the request of the client for an SDO and 0x058+NodeID the server's answer
- An overview of the CANProtocol can be found here: https://www.can-cia.org/fileadmin/resources/documents/brochures/co_poster.pdf
- For some reason, I cannot find any SDO request 0x060 from the NodeID 0x0A (0x060A). In earlier logs there are such requests. Maybe that's one point to investigate?
- The requested SDO can be found in byte 1 and 2. Byte 3 is the subindex followed by the corresponding data (BE)


Setup:
- Two OLS20 (both the latest and same FW)
- 125 kbit/s speed
- Addresses 0x0A and 0X0B
- PeakCAN USB Adapter
- Hardware: RaspberryPi 3


[20240131_candump_log.txt](https://github.com/SICKAG/sick_line_guidance/files/14108421/20240131_candump_log.txt)
[20240131_roslaunch_log.txt](https://github.com/SICKAG/sick_line_guidance/files/14108422/20240131_roslaunch_log.txt)

BR
T.J.

**Comment by rostest** [comment]
Many thanks for your informations and logfiles. Some anomalies after first viewing the log files:

There are two OLS devices with can id 0x0A ("OLS-A") and 0x0B ("OLS-B"). After initialization, the logfiles start with the first query:
* roslaunch:
   ```
   [ INFO] [1706553166.554772829]: sick_line_guidance::CanopenChain::queryCanObject(node1): [2021subB]=d
   [ INFO] [1706553166.555030381]: sick_line_guidance::CanSubscriber::MeasurementHandler: [2021subB]=0x64
   ```
* candump:
   ```
   (1706553166.549516)  can0  60B   [8]  40 21 20 0B 00 00 00 00 # request to OLS-B: [2021subB]
   (1706553166.553890)  can0  58B   [8]  4F 21 20 0B 64 00 00 00 # response from OLS-B: [2021subB]=0x64
   ```

For a while, the system is up and running and the can communication is okay.

After 25.710 seconds, the following error occures :
* roslaunch:
   ```
   [ INFO] [1706553192.265522246]: sick_line_guidance::CanopenChain::queryCanObject(node1): [2023sub1]=
   [ INFO] [1706553192.265756048]: sick_line_guidance::CanSubscriber::MeasurementHandler: [2023sub1]=0x00
   [ERROR] [1706553192.269867038]: Received error frame: 20000004#000c000000000000
   [ERROR] [1706553192.271138392]: internal error: 64
   [ INFO] [1706553192.273718965]: Current state: 2 device error: system:0 internal_error: 64 (bus off;)
   [ INFO] [1706553192.274016100]: Current state: 1 device error: system:0 internal_error: 64 (bus off;)
   [ERROR] [1706553192.276212871]: Received error frame: 20000040#0000000000000000
   [ERROR] [1706553192.278929486]: CAN not ready
   ```
* candump:
   ```
   (1706553192.261401)  can0  60B   [8]  40 23 20 01 00 00 00 00 # request to OLS-B: [2023sub1]
   (1706553192.262014)  can0  28A   [6]  00 00 18 00 00 00       # transmit PDO2 from OLS-A
   (1706553192.264762)  can0  58B   [8]  4F 23 20 01 00 00 00 00 # response from OLS-B: [2023sub1]=0x00
   (1706553192.267529)  can0  18B   [8]  00 00 02 00 00 00 02 00 # transmit PDO1 from OLS-B
   (1706553192.268395)  can0  080   [0]                          # regular SYNC message from can master
   (1706553192.270532)  can0  28B   [6]  00 00 18 00 00 00       # transmit PDO2 from OLS-B
   (1706553192.277021)  can0  18A   [8]  00 00 01 00 00 00 02 00 # transmit PDO1 from OLS-A
   ```
   
After that, the candump logs further PDOs (`can0 28B ...` and `can0 18A ...`), but there are no SYNC messages (`can0 080`) any longer in the candump.

Previously, SYNC messages (`can0 080`) are continously sent with 100 Hz by the can master. The next SYNC message would be expected at timestamp 1706553192.278, but there are no SYNC messages after timestamp 1706553192.268.

1.5 milliseconds after the last SYNC message (i.e. before the next regular SYNC is missing), roslaunch reports an error `Received error frame: 20000004#000c000000000000`, followed by `device error: system:0 internal_error: 64 (bus off;)`. This error message is generated in ros_canopen, function canopen::CANLayer::handleFrame in file ros_canopen/canopen_master/include/canopen_master/can_layer.h. Remarkable is that data array `000c000000000000` of the reported can::Frame can not be found in the candump.

Most probably, the can master implemented in package ros_canopen runs into a problem for some reason. The reason for this is currently unclear to me. The subsequent timeout exception in ros_canopen/canopen_master/src/sdo.cpp(429) is most probably only a consequential error.

**Comment by ghost** [comment]
Thank you for the very detailed analysis.

I just realized that I used a yaml file from earlier tests for the attached logs, where just one (0x0B) OLS20 were included. 
BUT, the error is exactly the same issue. This "wrong" configuration is also interesting in terms of that the failure occurred with one configured OLS20.

I'm now not even able to start `roslaunch` with both OLS20 for a few seconds. See attached log for both ols20.
[31012024_2xOLS20_roslaunch_log.txt](https://github.com/SICKAG/sick_line_guidance/files/14111944/31012024_2xOLS20_roslaunch_log.txt)

I just saw, that the information of the can-driver GIT claims that 

> The current develop branch is melodic-devel, it targets ROS melodic. Needs C++14 compiler. The released version gets synced over to the distro branch for each release.

I'm currently using ROS noetic (latest release). Do you think this could be a reason for the issues?
I'm still struggling to start a ROS node for each OLS. Seems like paths are not correct. I will keep you informed.

**Comment by rostest** [comment]
Thanks for following up! It explains why the last candump logs PDOs from two OLS20 devices (both are active), but only SDOs of OLS-B are queried and answered (there are no `can0  60A` messages in the candump).

In 31012024_2xOLS20_roslaunch_log.txt, the error occures immediately after start. Maybe another can master is already running?

**Comment by ghost** [comment]
Notice:
To eliminate further causes of errors, I ordered a new PCAN USB-Adapter (same type but new).
Found difference in performance of the used PCAN USB Adapters:

Old Adapter: FW2.8
New Adapter: FW8.6.1
Driver Version: 4.4.2

With Baudrate of 125 kBit/s and two OLS20, it runs much more stable. If an error occurs, it reinitializes itself and goes on. So far this seems to improve the communication a lot. 
Further testing pending.

**Comment by ghost** [comment]
Further investigations:

- Setting `double max_publish_rate` and `double max_query_rate` back to 1000 Hz
- Randomly measuring time span between two similar SDO requests of client using `candump -ta can0`
- Timespan between two same requests is approx. 100 ms, no matter whether 10 Hz or 1000 Hz is set.

What could be the reason for this?

**Comment by ghost** [comment]
Attached log of 2 OLS20, 125 kBit/s, "new" PCanUSB Adapter.
Duration ~52 min.

[20240201_log_candump_roslaunch_newPcan.zip](https://github.com/SICKAG/sick_line_guidance/files/14123962/20240201_log_candump_roslaunch_newPcan.zip)

Error at line 387332 (roslaunch log).
Log of candump also included.

**Comment by rostest** [comment]
Thanks for new logfiles. This time the error looks different:

Start at 1706781432.078092381 (roslaunch):
   ```
   [ INFO] [1706781432.078092381]: sick_line_guidance::CanopenChain::queryCanObject(node1): [2021subB]=d[0m
   [ INFO] [1706781432.078451391]: sick_line_guidance::CanSubscriber::MeasurementHandler: [2021subB]=0x64[0m
   ```

1.st error after 13.2 minutes (793.3 seconds):
* roslaunch:
   ```
   [ INFO] [1706782225.304435785]: sick_line_guidance::CanSubscriber::MeasurementHandler: [2023sub3]=0x00[0m
   [ INFO] [1706782225.307302240]: sick_line_guidance::OLS_Measurement: {position:[0.000,0.005,0.000],width:[0.000,0.024,0.000],status=0x02,devstatus=0x0000,error=0x00,barcode=0x
   [ERROR] [1706782225.362218070]: sick_line_guidance::CanopenChain::queryCanObject(): ServiceClient::call("/driver/get_object") failed.[0m
   [ERROR] [1706782225.362426403]: sick_line_guidance::CanopenChain::queryCanObject(" << node_id << "): shutdown and re-init can communication after SDO error[0m
   [ WARN] [1706782225.362748851]: sick_line_guidance::CanopenChain::shutdownCanDriver(): shutdown can communication by ServiceClient::call("/driver/shutdown")...[0m
   [ERROR] [1706782225.386715025]: not operational; CAN not ready[0m
   [ERROR] [1706782229.521519472]: sick_line_guidance::CanopenChain::queryCanObject(node1): [2023sub2]="" failed [0m
   [ERROR] [1706782229.521917545]: querySDO(2023sub2,uint8_t) failed
   ```
* candump looks normal at this time:
   ```
   (1706782225.353915)  can0  60B   [8]  40 23 20 01 00 00 00 00
   (1706782225.357404)  can0  080   [0] 
   (1706782225.358432)  can0  58B   [8]  4F 23 20 01 00 00 00 00
   (1706782225.361180)  can0  28A   [6]  00 00 18 00 00 00
   (1706782225.366411)  can0  18B   [8]  00 00 05 00 00 00 02 00
   (1706782225.367394)  can0  080   [0] 
   ```
* roslaunch logs: queryCanObject failed, response to SDO request (node1, 2023sub2) missing
* But candump shows that the last SDO request (node1, 2023sub2) before the error was successful:
   ```
   (1706782225.272402)  can0  60A   [8]  40 23 20 02 00 00 00 00
   (1706782225.276534)  can0  58A   [8]  4F 23 20 02 6A 00 00 00
   ```

2.nd error after 44.3 minutes (2660.3 seconds):
* roslaunch:
   ```
   [ INFO] [1706784092.354696598]: sick_line_guidance::CanopenChain::queryCanObject(node1): [2023sub1]=[0m
   [ INFO] [1706784092.354886650]: sick_line_guidance::CanSubscriber::MeasurementHandler: [2023sub1]=0x00[0m
   [ INFO] [1706784092.355012066]: sick_line_guidance::OLS_Measurement: {position:[0.000,0.005,0.000],width:[0.000,0.024,0.000],status=0x02,devstatus=0x0000,error=0x00,barcode=0x00,barcodecenter=0.000,linequality=0x64,lineintensity=[0x00,0x6B,0x00],status_ok=1,line_good=1}[0m
   [ERROR] [1706784092.407280592]: sick_line_guidance::CanopenChain::queryCanObject(): ServiceClient::call("/driver/get_object") failed.[0m
   [ERROR] [1706784092.407487206]: sick_line_guidance::CanopenChain::queryCanObject(" << node_id << "): shutdown and re-init can communication after SDO error[0m
   [ WARN] [1706784092.407720382]: sick_line_guidance::CanopenChain::shutdownCanDriver(): shutdown can communication by ServiceClient::call("/driver/shutdown")...[0m
   ```
* candump looks normal at this time:
   ```
   (1706784092.406878)  can0  18B   [8]  00 00 05 00 00 00 02 00
   (1706784092.406884)  can0  28B   [6]  00 00 19 00 00 00
   (1706784092.408348)  can0  28A   [6]  00 00 18 00 00 00
   (1706784092.408351)  can0  18A   [8]  00 00 05 00 00 00 02 00
   (1706784092.411730)  can0  080   [0] 
   ```
* roslaunch logs: queryCanObject failed, response to SDO request (node2, 2023sub1) missing
* But candump shows that the last SDO request before the error was successful:
   ```
   (1706784092.356741)  can0  60B   [8]  40 23 20 01 00 00 00 00
   (1706784092.361723)  can0  080   [0] 
   (1706784092.361989)  can0  58B   [8]  4F 23 20 01 00 00 00 00
   ```

The logfiles show two identical errors:
* A ros service call to canopen_chain_node (package ros_canopen) returns with error, i.e. the success flag returned by `serviceClient<canopen_chain_node::GetObject>("/driver/get_object")` is false for some reason
* sick_line_guidance initializes a can shutdown and re-init due to can communication error
* Successful recovering after can communication error

**Comment by ghost** [comment]
### All things, done the past weeks:

**Log recording**
- logging CANOpen
- logging ROS

**Analysis of logs**
- Analysis of RAW data
- comparison of ROS and CAN data logs
- see: [CanLog Analyser_2xOLS20.xlsx](https://github.com/SICKAG/sick_line_guidance/files/14511291/CanLog.Analyser_2xOLS20.xlsx)
- process of failure analysis (see below)

**Check of periphery**
- New PCAN USB adapter
- Check Ubuntu and ROS versions
As the customer is using it. ROS according to customer and according to ros_canopen driver --> no influence
- Termination checked
- FW of OLS20 checked

**Software issue checks**
- Found [similar issue](https://github.com/SICKAG/sick_line_guidance/issues/6) in this project
- Also tried the recommendation of this projects issue to add a respawn flag in the launch file. Did not help.
- Found similar issues in ros_canopen driver. [Example](https://github.com/ros-industrial/ros_canopen/issues/425) 

**Check of Config.**
- tested different configs of this project with your help (see this issue)

**CANOpen Bus**
- Bus load just at 10-13 %

**Ubuntu system tests**
- set higher prio for canopen process

**Tests with two MLS**
- First they run for approx. 3h
- After that, test with OLS20 and got immediately the mentioned error
- After that, again test with MLS and got the error as well...
- 125k Baud rate (IDs 0x0A and 0x0B) 

---------------------------------------------

**Detailed process of the failure:**
![image](https://github.com/SICKAG/sick_line_guidance/assets/158258534/bb143670-3376-4a03-b56d-0a1cea098110)

**Detailed process when script starts:**
![image](https://github.com/SICKAG/sick_line_guidance/assets/158258534/d7797b4b-00be-4582-a880-451c193974b9)

**Comment by ghost** [comment]
Thank you for the fix.

I have tested the new branch using two OLS20.
- I let it run with 125kBit for 7.5h **without error** (without stop of communication)
- I let it run with 500kBit for 4h (1.5h, 1.5h, 1h) **without error** (without stop of communication)

As a result, the fix does work great. Thanks!

One more thing: Can you adapt the topics (`rostopic list`) to the new config or create an alternative launch file with two OLS20?

**Comment by rostest** [comment]
Thank you very much for your feedback. An example launchfile [sick_line_guidance_ols20_twin.launch](https://github.com/SICKAG/sick_line_guidance/blob/master/launch/sick_line_guidance_ols20_twin.launch) for two OLS20 devices is added.
